version: "3.9"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  python:
    build: .
    command: [ "-a", "https://url/to/auth/api", "-u", "username", "-p", "password", "-m", "https://url/to/match/{id}/api" ]
    depends_on:
      - mongo
